### ISSUE TITLE
exec user process caused "no such file or directory" in v1.2.1

### ISSUE THREAD

**Issue by kunzese** [actionshub/markdownlint#10]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The current version 1.2.1 of this action fails with:

```
Run actionshub/markdownlint@1.2.1
/usr/bin/docker run ....
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

Seems to be fixed in _master_ with c8fe67f. Can you release a new version?

## :pancakes: Action version

v1.2.1

## :tophat: workflow configuration

https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action/blob/master/.github/workflows/test.yml

## Steps To Reproduce

1. Use it 😄 

## :police_car: Expected behavior

Linting and not failing.

## :heavy_plus_sign: Additional context

❤️

**Comment by Xorima** [comment]
Released as 1.2.2
