### ISSUE TITLE
Ignore a folder

### ISSUE THREAD

**Issue by fulldecent** [actionshub/markdownlint#19]
We would like to check all files in the repository (`.`) but then exclude files that are not ours (`/vendor`).

Currently file exclusions are not supported with path input.

**Comment by Xorima** [comment]
Have you tried in input `filesToIgnoreRegex`

**Comment by fulldecent** [comment]
@raza403 please see ^

**Comment by Xorima** [comment]
I will close this as I think it is resolved, if it isn't please reopen and we can continue the discussion

**Comment by Xorima** [comment]
Also @fulldecent  and @Raza403 an example of this working is: https://github.com/actionshub/chef-install/blob/main/.github/workflows/generic-linters.yml#L19-L27

**Comment by fulldecent** [comment]
Perfect, thank you

**Comment by Raza403** [comment]
@Xorima Thank you, it is working now, this helped a lot :+1:
