### ISSUE TITLE
Docker pull from ghcr not working for v2.1.1

### ISSUE THREAD

**Issue by brenner-tobias** [actionshub/markdownlint#26]
## :ghost: Brief Description

Using dependabot, the package was updated to new release v2.1.1 Unfortunately, the checkout from ghcr does not work:

> /usr/bin/docker pull ghcr.io/actionshub/markdownlint:v2.1.1
Error response from daemon: manifest unknown

## :pancakes: Action version

v2.1.1

## :tophat: workflow configuration

/usr/bin/docker pull ghcr.io/actionshub/markdownlint:v2.1.1

## Steps To Reproduce

1. Pull v2.1.1 from ghcr

**Comment by Xorima** [comment]
@brenner-tobias  try version v2.1.2 as I've reverted some recent changes.

**Comment by brenner-tobias** [comment]
Works now, thanks a lot @Xorima

**Comment by wopian** [comment]
This occurs again for 2.1.3

Logs: https://github.com/wopian/smooth-corners/actions/runs/4131187092/jobs/7142617904
