### ISSUE TITLE
Docker image v3.0.0 cannot be pulled

### ISSUE THREAD

**Issue by relusc** [actionshub/markdownlint#30]
## :ghost: Brief Description

When running the action, its image cannot be pulled.

```
Pull down action image 'ghcr.io/actionshub/markdownlint:v3.0.0'
  /usr/bin/docker pull ghcr.io/actionshub/markdownlint:v3.0.0
```

## :pancakes: Action version

latest version

## :tophat: workflow configuration

"vanilla" setup

```yaml
      - name: markdownlint-cli
        uses: actionshub/markdownlint@main
```

## Steps To Reproduce

Basically run the action, that's it 😄 

## :police_car: Expected behavior

Image should be pulled

**Comment by relusc** [comment]
seems to also be the case for images with different tags (e.g. `v2.1.0`), even using older versions of the image / the action leads to the same error

**Comment by damacus** [comment]
yeah latest, or an old tag will work. 

Here's a list of valid Docker tags
https://github.com/actionshub/markdownlint/pkgs/container/markdownlint

**Comment by damacus** [comment]
Apologies for being a guinea pig on this 😆

**Comment by wopian** [comment]
3.1.0 has the same issue
