### ISSUE TITLE
Container image tag v3.1.0 missing

### ISSUE THREAD

**Issue by tyll** [actionshub/markdownlint#35]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The Github action fails with:
```
Pull down action image 'ghcr.io/actionshub/markdownlint:v3.1.0'
  /usr/bin/docker pull ghcr.io/actionshub/markdownlint:v3.1.0
  Error response from daemon: manifest unknown
```
See https://github.com/linux-system-roles/network/actions/runs/4160529110/jobs/7197585345

v3.1.0 is not tagged:
https://github.com/actionshub/markdownlint/pkgs/container/markdownlint/versions?filters%5Bversion_type%5D=tagged

## :pancakes: Action version

main

## :tophat: workflow configuration

https://github.com/linux-system-roles/network/blob/main/.github/workflows/markdownlint.yml

## Steps To Reproduce

Create a PR with markdownlint workflow above

## :police_car: Expected behavior

markdownlint should run

## :heavy_plus_sign: Additional context

https://github.com/actionshub/markdownlint/pull/34 bumped the release but it seems it the workflow does not properly tag the container image.

**Comment by damacus** [comment]
Closed via #39
